### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by lyz0238** [rainwaltz/dmdsite#1]
Let's make a site for the students study Blockchain like us.

**Comment by rainwaltz** [comment]
멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍

**Comment by lyz0238** [comment]
> 멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍멍

**Comment by zerott88** [comment]
짜파게티 요리사
